baseurl = "https://www.depositfix.com"
title = "Payment Solution for HubSpot"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Integration Agent 2017"
disqusShortname = "integrationagent"


[author]
  name = "Denis Lunev"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "DepositFix"
  Author = "Denis Lunev"
  email = "denis@integrationagent.com"
  Ganalytics = "UA-7712728-16"

[[menu.main]]
  name = "Pricing"
  url = "/pricing"
  weight = -170
  style = "trial"

[[menu.main]]
  name = "About Us"
  url = "/about"
  weight = -160

[[menu.main]]
  name = "Login"
  url = "https://app.depositfix.com?ref=lp"
  weight = -150


[[menu.main]]
  name = "Start Your Free Trial"
  url = "/https://app.depositfix.com?ref=lp"
  weight = -140


